services:
  backend:
    build: ./backend/.
    tty: true
    working_dir: /home/node/app
    command: ["npm", "run", "start:dev"]
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:9229:9229"
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - PORT=3000
      - REDIS_ENCRYPTION_KEY=${REDIS_ENCRYPTION_KEY}
      - REDIS_URL=${REDIS_URL}
      - SESSION_SECRET=${SESSION_SECRET}
      - ZOOM_APP_CLIENT_ID=${ZOOM_APP_CLIENT_ID}
      - ZOOM_APP_CLIENT_SECRET=${ZOOM_APP_CLIENT_SECRET}
      - ZOOM_APP_CLIENT_URL=http://frontend:9090
      - ZOOM_APP_EXTERNAL_URL=http://127.0.0.1:3015
      - ZOOM_APP_REDIRECT_URI=${PUBLIC_URL}/api/zoomapp/auth
      - ZOOM_APP_OAUTH_STATE_SECRET=${ZOOM_APP_OAUTH_STATE_SECRET}
      - ZOOM_HOST=${ZOOM_HOST}
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - redis

  frontend:
    build: 
      context: ./frontend/.
      dockerfile: Dockerfile
    tty: true
    working_dir: /home/node/app
    command: "npm start"
    ports:
      - "127.0.0.1:3001:9090"
    environment:
      - PORT=9090
      - PUBLIC_URL=${PUBLIC_URL}/api/zoomapp/proxy
      - REACT_APP_PUBLIC_ROOT=${PUBLIC_URL}
      - REACT_APP_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - REACT_APP_AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - REACT_APP_AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules
      
  frontend_external:  # New frontend service for the external browser
    build: 
      context: ./frontend_external/. # Update this to the actual path of your external frontend app
      dockerfile: Dockerfile
    tty: true
    working_dir: /home/node/app
    command: ["npm", "run", "start"]
    stdin_open: true
    # Map the port inside the container to a port on your host machine (e.g., 3000:3000)
    ports:
      - "127.0.0.1:3015:9095" #  HOST_PORT:CONTAINER_PORT
    environment:
      - PORT=9095
      - CHOKIDAR_USEPOLLING=true 
      - WATCHPACK_POLLING=true # Hot reloading
      - PUBLIC_URL=${PUBLIC_URL}/api/videos/proxy
      - REACT_APP_PUBLIC_ROOT=${PUBLIC_URL}
    # Mount your app's source code as a volume so you can edit code without rebuilding
    volumes:
      - ./frontend_external:/home/node/app
      # - /home/node/app/node_modules 

  redis:
    image: redis:alpine
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./data:/data
